# This file was generated by GoReleaser. DO NOT EDIT.
cask "postman-sync" do
  name "postman-sync"
  desc "Sync an OpenAPI spec into a Postman collection while preserving manual customizations"
  homepage "https://github.com/akyrey/postman-sync"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postman-sync"

  on_macos do
    on_intel do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_darwin_amd64.tar.gz"
      sha256 "57f2c30f5e7aab84cc71b8bce9496e40793a3e2d4df40d34f39592514a805a90"
    end
    on_arm do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_darwin_arm64.tar.gz"
      sha256 "204c7bc0f19e7307bd0c6f3d52dc06f2104a249234e1911d67e08381ee1b817e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_linux_amd64.tar.gz"
      sha256 "d822c808945da3cb48361ba202dcac1e3e788a5526e2a67c7aac7a738b00113f"
    end
    on_arm do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_linux_arm64.tar.gz"
      sha256 "beb95352aec8722163b21a7e21c0d7a199ab849eb4fdee164a1c0453e74e4eb4"
    end
  end

  # No zap stanza required
end
