# This file was generated by GoReleaser. DO NOT EDIT.
cask "postman-sync" do
  name "postman-sync"
  desc "Sync an OpenAPI spec into a Postman collection while preserving manual customizations"
  homepage "https://github.com/akyrey/postman-sync"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postman-sync"

  on_macos do
    on_intel do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_darwin_amd64.tar.gz"
      sha256 "91fdcc7fef3d71c0b77967cc64198f615aefd9a4f566d22a2690493203fb4b6c"
    end
    on_arm do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_darwin_arm64.tar.gz"
      sha256 "79a084957cc68e8f35458866e6abfa49c728fe5fc86948f4e8373436df5b5f94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_linux_amd64.tar.gz"
      sha256 "d860103d43221499e91031d0612db1ae8733e3c69d42a937dd3c529fe949832a"
    end
    on_arm do
      url "https://github.com/akyrey/postman-sync/releases/download/v#{version}/postman-sync_#{version}_linux_arm64.tar.gz"
      sha256 "a8b3c692c3c7261530f8a7a6115d433163f2565b4862a30556c5cf2df389a3f1"
    end
  end

  # No zap stanza required
end
