# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector" do
  name "projector"
  desc "Run project commands across multiple directories"
  homepage "https://github.com/akyrey/projector"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  on_macos do
    on_intel do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_darwin_amd64.tar.gz"
      sha256 "97c6d09f5743cca53a21dd1d2383f66ca6c26c83b634ed6053a9b33af9049c02"
    end
    on_arm do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_darwin_arm64.tar.gz"
      sha256 "62f221cd71c906c2e6d8c118b59f57eb278b8d381826c601e51787be3516c5df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_linux_amd64.tar.gz"
      sha256 "c5a3b9744a888db4d63778be4ff9a56281ea8eeaf6fe8f0aa9937d625ebae7b3"
    end
    on_arm do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_linux_arm64.tar.gz"
      sha256 "7c1a6c727a205f7533434aa2686d865481a114a7c840be157c4698ff10ac52c3"
    end
  end

  # No zap stanza required
end
