# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_darwin_amd64.tar.gz"
      sha256 "7a03456b9a0694f6fdbf1275b9645558a6e2321a9249712d7cffc7427c3a991e"
    end
    on_arm do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_darwin_arm64.tar.gz"
      sha256 "771a78785cab5a1b8a9b2b32a58222f32328732722945d85a47b94c944b062cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_linux_amd64.tar.gz"
      sha256 "0083b775eb6ae7c166854913781f4e90da52de30fddd469088b39daf74559689"
    end
    on_arm do
      url "https://github.com/akyrey/projector/releases/download/v#{version}/projector_#{version}_linux_arm64.tar.gz"
      sha256 "4163e848f86e354baa208a3d0c2e9f4b82650b2bf3a936698d35d4e52a9e8ab5"
    end
  end

  name "projector"
  desc "Run project commands across multiple directories"
  homepage "https://github.com/akyrey/projector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  # No zap stanza required

end
