# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projector < Formula
  desc "Run project commands across multiple directories"
  homepage "https://github.com/akyrey/projector"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akyrey/projector/releases/download/v0.0.1/projector_0.0.1_darwin_amd64.tar.gz"
      sha256 "4edd0f3cdc7b5b75a5139e54930c4dbcf6a5bd0d8c267c9d226b5e6c47038ca9"

      define_method(:install) do
        bin.install "projector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akyrey/projector/releases/download/v0.0.1/projector_0.0.1_darwin_arm64.tar.gz"
      sha256 "b7dae7b87a3fe88a65bea134c513294180dcbff9990f874086788360ea442555"

      define_method(:install) do
        bin.install "projector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akyrey/projector/releases/download/v0.0.1/projector_0.0.1_linux_amd64.tar.gz"
      sha256 "b055f6934e6d019bd99deba6089e0c7d451b29f81df83c8e475d566d2b64ca35"
      define_method(:install) do
        bin.install "projector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akyrey/projector/releases/download/v0.0.1/projector_0.0.1_linux_arm64.tar.gz"
      sha256 "22bf2462e481bde4f21f2c8629335184adbde565f1f4f5e097371a071cb41344"
      define_method(:install) do
        bin.install "projector"
      end
    end
  end

  test do
    system "#{bin}/projector", "--version"
  end
end
